# --------------------------------------------------
# ISO (2-letter) -> Country
# --------------------------------------------------

ISO_TO_COUNTRY = {

    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AO": "Angola",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",

    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BR": "Brazil",
    "BN": "Brunei",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",

    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Republic of the Congo",
    "CD": "Democratic Republic of the Congo",
    "CR": "Costa Rica",
    "CI": "Côte d'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",

    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",

    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "SZ": "Eswatini",
    "ET": "Ethiopia",

    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",

    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GR": "Greece",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",

    "HT": "Haiti",
    "HN": "Honduras",
    "HU": "Hungary",

    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",

    "JM": "Jamaica",
    "JP": "Japan",
    "JO": "Jordan",

    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",

    "LA": "Laos",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LT": "Lithuania",
    "LU": "Luxembourg",

    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MX": "Mexico",
    "MD": "Moldova",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",

    "NA": "Namibia",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "MK": "North Macedonia",
    "NO": "Norway",

    "OM": "Oman",

    "PK": "Pakistan",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",

    "QA": "Qatar",

    "RO": "Romania",
    "RU": "Russia",
    "RW": "Rwanda",

    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "KR": "South Korea",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syria",

    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Türkiye",
    "TM": "Turkmenistan",

    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",

    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",

    "PS": "Palestine",
    "YE": "Yemen",

    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}


# -----------------------------
# MAPPINGS
# -----------------------------
zone_map = {}


zone_map.update({
    #Africa
    "Angola": "Africa",
    "Benin": "Africa",
    "Botswana": "Africa",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Cabo Verde": "Africa",
    "Cameroon": "Africa",
    "Cape Verde": "Africa",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Comoros": "Africa",
    "Republic of the Congo": "Africa",
    "Congo": "Africa",
    "Democratic Republic of Congo": "Africa",
    "Côte d'Ivoire": "Africa",
    "Ivory Coast": "Africa",
    "Equatorial Guinea": "Africa",
    "Eswatini": "Africa",
    "Eswatini, Kingdom of": "Africa",
    "Ethiopia": "Africa",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Ghana": "Africa",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Kenya": "Africa",
    "Lesotho": "Africa",
    "Liberia": "Africa",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Mali": "Africa",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Mozambique": "Africa",
    "Namibia": "Africa",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "Rwanda": "Africa",
    "Sao Tome and Principe": "Africa",
    "Senegal": "Africa",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "South Africa": "Africa",
    "South Sudan": "Africa",
    "Tanzania": "Africa",
    "Tanzania, United Republic of": "Africa",
    "Togo": "Africa",
    "Tunisia": "Africa",
    "Uganda": "Africa",
    "Zambia": "Africa",
    "Zimbabwe": "Africa",
    # Middle East and North Africa
    "Algeria": "Middle East and North Africa",
    "Bahrain": "Middle East and North Africa",
    "Egypt": "Middle East and North Africa",
    "Iran": "Middle East and North Africa",
    "Iran, Islamic Republic of": "Middle East and North Africa",
    "Iraq": "Middle East and North Africa",
    "Israel": "Middle East and North Africa",
    "Jordan": "Middle East and North Africa",
    "Kuwait": "Middle East and North Africa",
    "Lebanon": "Middle East and North Africa",
    "Libya": "Middle East and North Africa",
    "Morocco": "Middle East and North Africa",
    "Oman": "Middle East and North Africa",
    "Palestine": "Middle East and North Africa",
    "Qatar": "Middle East and North Africa",
    "Saudi Arabia": "Middle East and North Africa",
    "Sudan": "Middle East and North Africa",
    "Syria": "Middle East and North Africa",
    "Syrian Arab Republic": "Middle East and North Africa",
    "Tunisia": "Middle East and North Africa",
    "United Arab Emirates": "Middle East and North Africa",
    "Yemen": "Middle East and North Africa",
    "Djibouti": "Middle East and North Africa",
    "Somalia": "Middle East and North Africa",
    #Europe & Central Asia
    "Albania": "Europe & Central Asia",
    "Andorra": "Europe & Central Asia",
    "Armenia": "Europe & Central Asia",
    "Austria": "Europe & Central Asia",
    "Azerbaijan": "Europe & Central Asia",
    "Belarus": "Europe & Central Asia",
    "Belgium": "Europe & Central Asia",
    "Bosnia and Herzegovina": "Europe & Central Asia",
    "Bulgaria": "Europe & Central Asia",
    "Croatia": "Europe & Central Asia",
    "Cyprus": "Europe & Central Asia",
    "Czech Republic": "Europe & Central Asia",
    "Denmark": "Europe & Central Asia",
    "Estonia": "Europe & Central Asia",
    "Finland": "Europe & Central Asia",
    "France": "Europe & Central Asia",
    "Georgia": "Europe & Central Asia",
    "Germany": "Europe & Central Asia",
    "Greece": "Europe & Central Asia",
    "Hungary": "Europe & Central Asia",
    "Iceland": "Europe & Central Asia",
    "Ireland": "Europe & Central Asia",
    "Italy": "Europe & Central Asia",
    "Kazakhstan": "Europe & Central Asia",
    "Kyrgyzstan": "Europe & Central Asia",
    "Latvia": "Europe & Central Asia",
    "Lithuania": "Europe & Central Asia",
    "Luxembourg": "Europe & Central Asia",
    "Malta": "Europe & Central Asia",
    "Moldova": "Europe & Central Asia",
    "Monaco": "Europe & Central Asia",
    "Montenegro": "Europe & Central Asia",
    "Netherlands": "Europe & Central Asia",
    "North Macedonia": "Europe & Central Asia",
    "Norway": "Europe & Central Asia",
    "Poland": "Europe & Central Asia",
    "Portugal": "Europe & Central Asia",
    "Romania": "Europe & Central Asia",
    "Russia": "Europe & Central Asia",
    "Serbia": "Europe & Central Asia",
    "Slovakia": "Europe & Central Asia",
    "Slovenia": "Europe & Central Asia",
    "Spain": "Europe & Central Asia",
    "Sweden": "Europe & Central Asia",
    "Switzerland": "Europe & Central Asia",
    "Tajikistan": "Europe & Central Asia",
    "Turkey": "Europe & Central Asia",
    "Ukraine": "Europe & Central Asia",
    "United Kingdom": "Europe & Central Asia",
    "Liechtenstein": "Europe & Central Asia",
    "San Marino": "Europe & Central Asia",
    #Asia Pacific
    "Afghanistan": "Asia Pacific",
    "Australia": "Asia Pacific",
    "Bangladesh": "Asia Pacific",
    "Bhutan": "Asia Pacific",
    "Brunei": "Asia Pacific",
    "Cambodia": "Asia Pacific",
    "China": "Asia Pacific",
    "Fiji": "Asia Pacific",
    "India": "Asia Pacific",
    "Indonesia": "Asia Pacific",
    "Japan": "Asia Pacific",
    "Kiribati": "Asia Pacific",
    "Laos": "Asia Pacific",
    "Lao People's Democratic Republic": "Asia Pacific",
    "Malaysia": "Asia Pacific",
    "Maldives": "Asia Pacific",
    "Marshall Islands": "Asia Pacific",
    "Micronesia, Federated States of": "Asia Pacific",
    "Mongolia": "Asia Pacific",
    "Myanmar": "Asia Pacific",
    "Nepal": "Asia Pacific",
    "New Zealand": "Asia Pacific",
    "North Korea": "Asia Pacific",
    "Pakistan": "Asia Pacific",
    "Palau": "Asia Pacific",
    "Papua New Guinea": "Asia Pacific",
    "Philippines": "Asia Pacific",
    "South Korea": "Asia Pacific",
    "Sri Lanka": "Asia Pacific",
    "Thailand": "Asia Pacific",
    "Timor-Leste": "Asia Pacific",
    "Tonga": "Asia Pacific",
    "Tuvalu": "Asia Pacific",
    "Vanuatu": "Asia Pacific",
    "Vietnam": "Asia Pacific",
    "Viet Nam": "Asia Pacific",
    # Americas
    "Antigua and Barbuda": "Americas",
    "Argentina": "Americas",
    "Bahamas": "Americas",
    "Barbados": "Americas",
    "Belize": "Americas",
    "Bolivia": "Americas",
    "Brazil": "Americas",
    "Canada": "Americas",
    "Chile": "Americas",
    "Colombia": "Americas",
    "Costa Rica": "Americas",
    "Cuba": "Americas",
    "Dominica": "Americas",
    "Dominican Republic": "Americas",
    "Ecuador": "Americas",
    "El Salvador": "Americas",
    "Grenada": "Americas",
    "Guatemala": "Americas",
    "Guyana": "Americas",
    "Haiti": "Americas",
    "Honduras": "Americas",
    "Jamaica": "Americas",
    "Mexico": "Americas",
    "Nicaragua": "Americas",
    "Panama": "Americas",
    "Paraguay": "Americas",
    "Peru": "Americas",
    "Saint Kitts and Nevis": "Americas",
    "Saint Lucia": "Americas",
    "Saint Vincent and the Grenadines": "Americas",
    "Suriname": "Americas",
    "Trinidad and Tobago": "Americas",
    "United States": "Americas",
    "Uruguay": "Americas",
    "Venezuela": "Americas"
    })


disaster_map = {
    "Drought": "Climatological",
    "Heat Wave": "Climatological",
    "Cold Wave": "Climatological",


    "Epidemic": "Biological",
    "Pandemic": "Biological",


    "Earthquake": "Geophysical",
    "Tsunami": "Geophysical",
    "Volcanic eruption": "Geophysical",
    "Landslide": "Geophysical",


    "Cyclone": "Meteorological",
    "Storm": "Meteorological",


    "Flood": "Hydrological",
    "Flash Flood": "Hydrological",


    "Wildfire": "Non-technological and man-made",
    "Fire": "Non-technological and man-made",


    "Population movement": "Human-related",
    
    "Complex Emergency": "Complex Emergency",


    "Other": "Other"
    }





def iso_to_country(iso):
    if iso is None:
        return None
    return ISO_TO_COUNTRY.get(str(iso).upper())


def country_to_zone(country):
    if country is None:
        return None
    return COUNTRY_TO_ZONE.get(country)


def disaster_category(disaster_type):
    if disaster_type is None:
        return "Other"

    disaster_type = disaster_type.lower()

    for key, value in DISASTER_CATEGORY.items():
        if key.lower() in disaster_type:
            return value

    return "Other"
